name: Run script every 10 minutes

on:
    schedule:
        - cron: "*/10 * * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm ci

            - name: Run script
              run: node main.js
              env:
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
                  EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
                  RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
